#!/bin/bash

if [ "$#" != "1" ]; then
    echo "Usage $0 <source_dir>"
    exit 1
fi

source_dir=$1
tags_file=TAGS
temp_tags_file=${tags_file}.tmp

cd $source_dir

if [ ! -f $tags_file ]; then
    touch $tags_file
fi

find . \( -name '*.php' -or -name '*.py' -or -name '*.c' -or -name '*.java' \) -print0 | while IFS= read -r -d '' source_file; do
    etags -o $temp_tags_file -a "$source_file"
done

diff $temp_tags_file $tags_file

if [ "$?" != "0" ]; then
    cp $temp_tags_file $tags_file
fi

rm $temp_tags_file
